language: python
sudo: required

services:
  - docker

script:
  - docker run -v $PWD:/output gabrielmilan/lorenzett:sdumont -f PythiaGenerator/generate_zee.py -e 1 -p 0 -o first_test.root --bc_id_start -8 --bc_id_end 7
